### ISSUE TITLE
RTSP video not recording in Android

### ISSUE THREAD

**Issue by AndreySkyFoxSidorov** [mavlink/qgroundcontrol#10366]
## Expected Behavior
RTSP video recording not working
I think the problem is the wrong choice of video codec h265/264. Perhaps you need to add a field with the choice of codec to the settings for rtsp:
sinkCaps = gst_caps_from_string("video/x-h264,stream-format=avc"); 
sinkCaps = gst_caps_from_string("video/x-h265,stream-format=hvc1");

## Current Behavior
[D] at qrc:/qml/QGroundControl/FlightMap/PhotoVideoControl.qml:103 - "toggleShooting true"
[!] at ../../qgroundcontrol/qgroundcontrol/src/VideoReceiver/GstVideoReceiver.cc:531 - "Failed to link valve and file sink "rtsp://192.168.144.25:8554/ch01.264""

## Steps to Reproduce:
1. Build Android ( Commit: 2f14b59793167e885b50a71bcfe1a8c8cfcff071 [2f14b59] ) or Install Release version v4.2.3
2. Run qgroundcontrol
3. Set rtsp settings. 
4. Open camera. 
5. I can see the video, but an error occurs.
[D] at qrc:/qml/QGroundControl/FlightMap/PhotoVideoControl.qml:103 - "toggleShooting true"
[!] at ../../qgroundcontrol/qgroundcontrol/src/VideoReceiver/GstVideoReceiver.cc:531 - "Failed to link valve and file sink "rtsp://192.168.144.25:8554/ch01.264""

## System Information
When posting bug reports, include the following information
- Operating System: [Android 9, FPV SIYI MK15 ]
- Flight Controller: [Pixhawk]
- Qgroundcontrol: version v4.2.3

## Detailed Description
I think the problem is the wrong choice of video codec h265/264. Perhaps you need to add a field with the choice of codec to the settings for rtsp:
sinkCaps = gst_caps_from_string("video/x-h264,stream-format=avc"); 
sinkCaps = gst_caps_from_string("video/x-h265,stream-format=hvc1");

## Log Files and Screenshots
[D] at qrc:/qml/QGroundControl/FlightMap/PhotoVideoControl.qml:103 - "toggleShooting true"
[!] at ../../qgroundcontrol/qgroundcontrol/src/VideoReceiver/GstVideoReceiver.cc:531 - "Failed to link valve and file sink "rtsp://192.168.144.25:8554/ch01.264""

**Comment by jensensi** [comment]
Hello,

I also experience the same behavior on my Android device, when following the same steps.
Video is displayed on the device, but the recording fails.

- I receive the video stream over RTSP.
- I have selected mkv as the recording format.

When I build to Windows and run on a PC, the recording is initiated perfect.
When I build to Android and run on my device, the software is unable to link _recorderValve and _fileSink in GstVideoReceiver.cc

Module:  GstVideoReceiver.cc
Function:  void GstVideoReceiver::startRecording(const QString& videoFile, FILE_FORMAT format)
Call:  gst_element_link(_recorderValve, _fileSink) return FALSE

**System Information**

- Operating System: [Android 9, FPV SIYI MK15 ]
- Qgroundcontrol: version v4.2.3
- Gstreamer: 1.18.1 (on both Windows and Android, same behavior with 1.18.5 on Android)

Codec information when streaming to VLC (on Android and Windows).

- Codec: MPEG-H Part2/HEVC (H.265) (hevc)
- Type: Video
- Viceo resolution: 2560x 1440
- Frame rate: 29.970030

**Detailed Description**
I have investigated the template and pad information in _recorderValve and _fileSink using qCDebug traces based on
"Basic tutorial 6: Media formats and Pad Capabilities"
https://gstreamer.freedesktop.org/documentation/tutorials/basic/media-formats-and-pad-capabilities.html?gi-language=c

**Findings: (so far)**
The 'src pad' capabilities change from Windows to Android.

      video/x-h265
              alignment: au
          stream-format: hvc1		->  changed from 'hvc1' in Windows to 'byte-stream' in Android (?)
                 parsed: true
                  width: 2560
                 height: 1440
          chroma-format: 4:2:0
         bit-depth-luma: 8
       bit-depth-chroma: 8
            colorimetry: 1:3:5:1
                profile: main
                   tier: main
                  level: 5.1

_Questions: (to investigate further)_
Is this a valid reason why _recorderValve and _fileSink is unable to link?
Why do the 'src pad' capabilities change from Windows to Android when the stream is unchanged?


**Log Files and Screenshots**

_Windows: (success)_

```
Starting recording "rtsp://192.168.0.130:554/1"
New video file: "C:/Users/Privat/Documents/QGroundControl Daily/Video/2022-08-18_16.35.59.mkv"  "rtsp://192.168.0.130:554/1"

Pad Templates for RTSP packet receiver:
  SRC template: 'stream_%u'
    Availability: Sometimes
    Capabilities:
      application/x-rtp
      application/x-rdt

Pad Templates for File Sink:
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      ANY

Caps for the src pad:
      video/x-h265
              alignment: au
          stream-format: hvc1
                 parsed: true
                  width: 2560
                 height: 1440
          chroma-format: 4:2:0
         bit-depth-luma: 8
        bit-depth-chroma: 8
            colorimetry: 1:3:5:1
                profile: main
                   tier: main
                  level: 5.1
             codec_data: 010160000000b0000000000099f000fcfdf8f800000f02200001001740010c01ffff016000000300b00000030000030099ac092100010022420101016000000300b00000030000030099a001402005a1636bb932fcdc04040402

Caps for the sink pad:
      video/mpeg
            mpegversion: { (int)1, (int)2, (int)4 }
           systemstream: false
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-h264
          stream-format: avc
              alignment: au
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-h265
          stream-format: hvc1
              alignment: au
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-divx
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-huffyuv
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-dv
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-h263
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-msmpeg
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      image/jpeg
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-theora
      video/x-dirac
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-pn-realvideo
              rmversion: [ 1, 4 ]
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-vp8
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-vp9
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-raw
                 format: { (string)YUY2, (string)I420, (string)YV12, (string)UYVY, (string)AYUV, (string)GRAY8, (string)BGR, (string)RGB }
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-prores
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-wmv
             wmvversion: [ 1, 3 ]
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-av1
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]

Recording started "rtsp://192.168.0.130:554/1"

```

_Android: (fail to link)_

```
Starting recording "rtsp://192.168.0.130:554/1"
New video file: "/storage/emulated/0/QGroundControl Daily/Video/2022-08-18_21.40.58.mkv"  "rtsp://192.168.0.130:554/1"

Pad Templates for RTSP packet receiver:
  SRC template: 'stream_%u'
    Availability: Sometimes
    Capabilities:
      application/x-rtp
      application/x-rdt

  SINK template: 'sink'
    Availability: Always
    Capabilities:
      ANY

Caps for the src pad:
      video/x-h265
                  width: 2560
                 height: 1440
              framerate: [ 0/1, 2147483647/1 ]
                 parsed: true
          stream-format: byte-stream
              alignment: au
                profile: main
          chroma-format: 4:2:0
         bit-depth-luma: 8
       bit-depth-chroma: 8
            colorimetry: 1:3:5:1
                   tier: main
                  level: 5.1
      video/x-h265
              alignment: au
          stream-format: byte-stream
                 parsed: true
                  width: 2560
                 height: 1440
          chroma-format: 4:2:0
         bit-depth-luma: 8
       bit-depth-chroma: 8
            colorimetry: 1:3:5:1
                profile: main
                   tier: main
                  level: 5.1

Caps for the sink pad:
      video/mpeg
            mpegversion: { (int)1, (int)2, (int)4 }
           systemstream: false
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-h264
          stream-format: avc
              alignment: au
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-h265
          stream-format: hvc1
              alignment: au
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-divx
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-huffyuv
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-dv
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-h263
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-msmpeg
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      image/jpeg
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-theora
      video/x-dirac
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-pn-realvideo
              rmversion: [ 1, 4 ]
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-vp8
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-vp9
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-raw
                 format: { (string)YUY2, (string)I420, (string)YV12, (string)UYVY, (string)AYUV, (string)GRAY8, (string)BGR, (string)RGB }
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-prores
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-wmv
             wmvversion: [ 1, 3 ]
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-av1
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]

Failed to link valve and file sink "rtsp://192.168.0.130:554/1"

```
